#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef ATOMSDK_SWIFT_H
#define ATOMSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AtomCore;
@import Foundation;
@import ObjectiveC;
@import SystemExtensions;
#endif

#import <AtomSDK/AtomSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AtomSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class AtomCountry;
@class AtomLocation;
@class NSString;
@interface AtomManager (SWIFT_EXTENSION(AtomSDK))
- (AtomCountry * _Nullable)findClosestCountryWithUserLocation:(AtomCountry * _Nonnull)userLocation countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (AtomLocation * _Nullable)findClosestLocationWithUserLocation:(AtomCountry * _Nonnull)userLocation countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (AtomCountry * _Nullable)findCountryWithCountry:(AtomCountry * _Nonnull)country countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (void)shouldAllowDialingWithIPWithDomain:(NSString * _Nonnull)domain completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

enum AtomOnDemandRuleType : NSInteger;
enum AtomOnDemandInterfaceType : NSInteger;
@class NSURL;
/// Base class for Atom On-Demand VPN rules.
/// This class provides the common properties for all types of On-Demand rules,
/// such as the rule type, interface type, SSID match, DNS match, and probe URL.
/// Use subclasses such as <code>AtomOnDemandConnectRule</code>, <code>AtomOnDemandDisconnectRule</code>,
/// <code>AtomOnDemandIgnoreRule</code>, or <code>AtomOnDemandEvaluateConnectionRule</code> for specific behaviors.
SWIFT_CLASS("_TtC7AtomSDK16AtomOnDemandRule")
@interface AtomOnDemandRule : NSObject
/// The type of the On-Demand rule.
@property (nonatomic, readonly) enum AtomOnDemandRuleType type;
/// Optional array of Wi-Fi SSIDs to match.
/// If nil, the rule applies to all SSIDs.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable SSIDMatch;
/// Optional array of DNS search domains to match.
/// If nil, the rule does not evaluate search domains.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsSearchDomains;
/// Optional array of DNS server IP addresses to match.
/// If nil, the rule does not evaluate DNS server addresses.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsServerAddresses;
/// The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any).
/// Default is <code>.any</code>.
@property (nonatomic) enum AtomOnDemandInterfaceType interfaceType;
/// Optional HTTP or HTTPS URL to probe for connectivity.
/// The VPN may start based on the result of this probe.
@property (nonatomic, copy) NSURL * _Nullable probeURL;
/// Initializes a new AtomOnDemandRule with the specified rule type.
/// \param type The type of the On-Demand rule (connect, disconnect, ignore, or evaluate connection).
///
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an On-Demand VPN rule that triggers the VPN to connect automatically.
/// Use this rule to specify when the VPN should start connecting based on network interfaces
/// and optional Wi-Fi SSIDs. This class is part of the AtomSDK On-Demand rules system.
SWIFT_CLASS("_TtC7AtomSDK23AtomOnDemandConnectRule")
@interface AtomOnDemandConnectRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandConnectRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Represents an On-Demand VPN rule that triggers the VPN to disconnect automatically.
/// Use this rule to specify when the VPN should stop or disconnect based on network interfaces
/// and optional Wi-Fi SSIDs. This class is part of the AtomSDK On-Demand rules system.
SWIFT_CLASS("_TtC7AtomSDK26AtomOnDemandDisconnectRule")
@interface AtomOnDemandDisconnectRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandDisconnectRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

@class AtomOnDemandEvaluateConnectionRuleItem;
/// Represents an On-Demand VPN rule that evaluates network connections and determines
/// whether the VPN should connect based on the defined connection rule items.
/// This rule type is part of the AtomSDK On-Demand rules system. It allows specifying multiple
/// destinations and corresponding actions to fine-tune when the VPN should start automatically.
SWIFT_CLASS("_TtC7AtomSDK34AtomOnDemandEvaluateConnectionRule")
@interface AtomOnDemandEvaluateConnectionRule : AtomOnDemandRule
/// An array of AtomOnDemandEvaluateConnectionRuleItem objects.
/// Each item is evaluated in order against network connections to determine the VPN action.
@property (nonatomic, copy) NSArray<AtomOnDemandEvaluateConnectionRuleItem *> * _Nullable connectionRules;
/// Initializes a new AtomOnDemandEvaluateConnectionRule.
/// \param connectionRules An array of AtomOnDemandEvaluateConnectionRuleItem objects defining the evaluation rules.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithConnectionRules:(NSArray<AtomOnDemandEvaluateConnectionRuleItem *> * _Nonnull)connectionRules interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Specifies the action to take when a network connection matches an Atom On-Demand Evaluate Connection rule item.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandEvaluateConnectionRuleAction, open) {
/// Start the VPN if connections to the matching hostname cannot be resolved.
  AtomOnDemandEvaluateConnectionRuleActionConnectIfNeeded = 0,
/// Do not start the VPN.
  AtomOnDemandEvaluateConnectionRuleActionNeverConnect = 1,
};

/// Represents a single connection evaluation rule item for Atom On-Demand Evaluate Connection rules.
/// Each item defines a set of destination domains and the action to take if a network connection
/// matches any of these domains. Optionally, DNS servers and a probe URL can be provided to assist
/// in evaluating connectivity.
SWIFT_CLASS("_TtC7AtomSDK38AtomOnDemandEvaluateConnectionRuleItem")
@interface AtomOnDemandEvaluateConnectionRuleItem : NSObject
/// The list of destination host domains to match against.
/// If the host name of the network connection being established matches any of these domains,
/// this rule item is considered applicable.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull matchDomains;
/// The action to take when the connection matches this rule item.
@property (nonatomic, readonly) enum AtomOnDemandEvaluateConnectionRuleAction action;
/// Optional DNS servers to use when evaluating connectivity to the destination hosts.
/// Used if <code>action</code> is <code>connectIfNeeded</code>.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsServers;
/// Optional HTTP or HTTPS URL to probe for connectivity.
/// If the probe request fails (e.g., returns a non-200 response) and <code>action</code> is <code>connectIfNeeded</code>,
/// the VPN is started.
@property (nonatomic, copy) NSURL * _Nullable probeURL;
/// Initializes a new AtomOnDemandEvaluateConnectionRuleItem.
/// \param matchDomains An array of host domains to match.
///
/// \param action The action to take when the network connection matches one of the domains.
///
/// \param dnsServers Optional array of DNS servers for evaluating connectivity.
///
/// \param probeURL Optional URL to probe for connectivity.
///
- (nonnull instancetype)initWithMatchDomains:(NSArray<NSString *> * _Nonnull)matchDomains action:(enum AtomOnDemandEvaluateConnectionRuleAction)action dnsServers:(NSArray<NSString *> * _Nullable)dnsServers probeURL:(NSURL * _Nullable)probeURL OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an On-Demand VPN rule that leaves the VPN connection state unchanged.
/// Use this rule to specify networks or conditions where the VPN should neither connect nor disconnect.
/// The current VPN connection state is preserved when this rule matches.
SWIFT_CLASS("_TtC7AtomSDK22AtomOnDemandIgnoreRule")
@interface AtomOnDemandIgnoreRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandIgnoreRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Represents the network interface type to which an Atom On-Demand rule applies.
/// Use this to specify whether a rule applies to Wi-Fi, Cellular, Ethernet, or any network interface.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandInterfaceType, open) {
/// The rule applies to any network interface.
  AtomOnDemandInterfaceTypeAny = 0,
/// The rule applies to Ethernet connections (macOS and tvOS only).
  AtomOnDemandInterfaceTypeEthernet = 1,
/// The rule applies to Wi-Fi connections.
  AtomOnDemandInterfaceTypeWifi = 2,
/// The rule applies to Cellular connections (iOS only).
  AtomOnDemandInterfaceTypeCellular = 3,
};

/// Represents the type of an Atom On-Demand VPN rule.
/// Used to indicate the action that should be taken when a network connection
/// matches the conditions of the rule.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandRuleType, open) {
/// Start the VPN connection when the rule matches.
  AtomOnDemandRuleTypeConnect = 0,
/// Disconnect the VPN connection when the rule matches.
  AtomOnDemandRuleTypeDisconnect = 1,
/// Leave the VPN connection state unchanged when the rule matches.
  AtomOnDemandRuleTypeIgnore = 2,
/// Evaluate the network connection against a set of connection rules
/// and determine whether the VPN should connect.
  AtomOnDemandRuleTypeEvaluateConnection = 3,
};

SWIFT_CLASS("_TtC7AtomSDK32AtomSDKDarwinNotificationManager")
@interface AtomSDKDarwinNotificationManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AtomSDKDarwinNotificationManager * _Nonnull shared;)
+ (AtomSDKDarwinNotificationManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)postNotificationWithName:(NSString * _Nonnull)name userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
- (void)startObservingWithName:(NSString * _Nonnull)name callback:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable))callback;
- (void)stopObservingWithName:(NSString * _Nonnull)name;
@end

SWIFT_CLASS("_TtC7AtomSDK13AtomSDKLogger")
@interface AtomSDKLogger : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL IS_AUTOMATION_LOGS_ENABLED;)
+ (BOOL)IS_AUTOMATION_LOGS_ENABLED SWIFT_WARN_UNUSED_RESULT;
+ (void)automationLoggerWithStr:(NSString * _Nonnull)str;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents the configuration parameters for AtomShield functionality.
SWIFT_CLASS("_TtC7AtomSDK16AtomShieldConfig")
@interface AtomShieldConfig : NSObject
/// The IP address for the AtomShield socket connection.
@property (nonatomic, copy) NSString * _Nonnull socketIP;
/// The port number for the AtomShield socket connection.
@property (nonatomic, copy) NSString * _Nonnull socketPort;
/// The features array for the AtomShield services.
@property (nonatomic, strong) NSArray * _Nonnull atomShieldFeatures;
/// The maximum number of retry attempts for establishing a Tracker Blocker socket connection.
@property (nonatomic) NSInteger retryCountForTBSocketConnection;
/// The time interval, in seconds, for updating the Tracker Blocker.
@property (nonatomic) NSInteger timeIntervalForTBUpdateInSeconds;
/// The timeout duration, in seconds, for the Tracker Blocker socket connection.
@property (nonatomic) NSInteger timeoutForTBSocketConnectionInSeconds;
/// Initializes a new instance of <code>AtomShieldConfig</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7AtomSDK14AtomShieldData")
@interface AtomShieldData : NSObject
- (NSInteger)getTotalCount SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <code>AtomShieldMPStats</code> is an Objective-C compatible class representing statistics related to telemetries.
/// note:
/// This class inherits from <code>NSObject</code> to support Objective-C interoperability.
SWIFT_CLASS("_TtC7AtomSDK17AtomShieldMPStats")
@interface AtomShieldMPStats : NSObject
/// The IP address of the socket.
@property (nonatomic, copy) NSString * _Nonnull socketIP;
/// The port of the socket.
@property (nonatomic, copy) NSString * _Nonnull socketPort;
/// The response received from the socket.
@property (nonatomic, copy) NSString * _Nonnull socketResponse;
/// The error code associated with the socket.
@property (nonatomic) NSInteger socketErrorCode;
/// The error message associated with the socket.
@property (nonatomic, copy) NSString * _Nonnull socketErrorMessage;
/// Additional inner error message associated with the socket.
@property (nonatomic, copy) NSString * _Nonnull socketErrorInnerMessage;
/// The type of feature requested by user.
@property (nonatomic, copy) NSString * _Nonnull featureType;
/// Initializes a new instance of <code>AtomShieldMPStats</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AtomShieldManagerDelegate;
@class NSError;
/// Manages the socket connection and provides methods to start, stop, and manage Atom Shield features.
SWIFT_CLASS("_TtC7AtomSDK17AtomShieldManager")
@interface AtomShieldManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onSendAtomShieldTelemetriesClosure)(NSInteger, AtomShieldMPStats * _Nullable);
@property (nonatomic, strong) id <AtomShieldManagerDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AtomShieldManager * _Nonnull shared;)
+ (AtomShieldManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isAtomShieldConnected;
/// Default init method for the class.
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Starts the connection to the AtomShieldService with the given shield configurations.
/// \param atomShieldConfig The atomShield configurations.
///
- (void)startConnectionWithAtomShieldConfig:(AtomShieldConfig * _Nonnull)atomShieldConfig isReconnecting:(BOOL)isReconnecting;
- (void)stopConnectionWithCompletionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
/// Executes an error with the given shield status.
/// \param status The AtomShield status.
///
/// \param error The AtomShield error.
///
/// \param message The AtomShield message.
///
- (void)executeErrorWithStatus:(AtomShieldStatus)status error:(NSError * _Nullable)error message:(NSString * _Nullable)message;
@end

/// Interface for receiving callbacks related to AtomShield events.
SWIFT_PROTOCOL("_TtP7AtomSDK25AtomShieldManagerDelegate_")
@protocol AtomShieldManagerDelegate
/// Invokes when the status of AtomShield changes.
/// \param status The AtomShield status.
///
/// \param error The AtomShield error.
///
/// \param message The AtomShield message.
///
- (void)onAtomShieldStatusChangeWithStatus:(AtomShieldStatus)status error:(NSError * _Nullable)error message:(NSString * _Nullable)message;
/// Invokes when data related to AtomShield, such as tracker blocker information, is received.
/// \param data The AtomShield data.
///
- (void)onAtomShieldDataReceivedWithData:(AtomShieldData * _Nullable)data;
@end

@class AccessTokenModel;
@class ApiBaseUrlModel;
@class AtomConfiguration;
SWIFT_CLASS("_TtC7AtomSDK14Authentication")
@interface Authentication : NSObject <ManagerProtocol>
@property (nonatomic, strong) AccessTokenModel * _Nullable accessToken;
@property (nonatomic, copy) NSString * _Nullable activeBaseUrl;
@property (nonatomic, strong) ApiBaseUrlModel * _Nullable apiUrl;
@property (nonatomic, strong) AtomConfiguration * _Nullable atomConfiguration;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Authentication * _Nonnull sharedManager;)
+ (Authentication * _Nonnull)sharedManager SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedManager:(Authentication * _Nonnull)value;
+ (void)setupWithAtomConfiguration:(AtomConfiguration * _Nullable)atomConfiguration baseUrlModel:(ApiBaseUrlModel * _Nonnull)baseUrlModel activeURL:(NSString * _Nullable)activeURL;
- (void)generateAccessTokenWithAuthToken:(void (^ _Nonnull)(AccessTokenModel * _Nullable, NSError * _Nullable))authToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum InternetAvailablity : NSInteger;
SWIFT_PROTOCOL("_TtP7AtomSDK20ConnectivityDelegate_")
@protocol ConnectivityDelegate
- (void)updateConnectionStatus:(enum InternetAvailablity)status;
@end

SWIFT_CLASS("_TtC7AtomSDK18ConnectivityHelper")
@interface ConnectivityHelper : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ConnectivityHelper * _Nonnull shared;)
+ (ConnectivityHelper * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hostNames;
@property (nonatomic) NSInteger hostIndex;
@property (nonatomic, strong) id <ConnectivityDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startHostAt:(NSInteger)index;
- (void)setupReachability:(NSString * _Nullable)hostName useClosures:(BOOL)useClosures;
- (void)startNotifier;
- (void)stopNotifier;
- (void)stopConnectivityChecks;
- (void)checkBrowsingWithUrl:(NSString * _Nonnull)withUrl withCompletion:(void (^ _Nonnull)(BOOL))withCompletion;
@end

SWIFT_CLASS("_TtC7AtomSDK15ExtensionHolder") SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface ExtensionHolder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class OSSystemExtensionRequest;
@class OSSystemExtensionProperties;
SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionHolder (SWIFT_EXTENSION(AtomSDK)) <OSSystemExtensionRequestDelegate>
- (void)request:(OSSystemExtensionRequest * _Nonnull)request didFinishWithResult:(OSSystemExtensionRequestResult)result;
- (OSSystemExtensionReplacementAction)request:(OSSystemExtensionRequest * _Nonnull)request actionForReplacingExtension:(OSSystemExtensionProperties * _Nonnull)existing withExtension:(OSSystemExtensionProperties * _Nonnull)ext SWIFT_WARN_UNUSED_RESULT;
- (void)requestNeedsUserApproval:(OSSystemExtensionRequest * _Nonnull)request SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)request:(OSSystemExtensionRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end

@protocol ExtensionManagerDelegate;
SWIFT_CLASS("_TtC7AtomSDK16ExtensionManager") SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionManager : NSObject
@property (nonatomic, weak) id <ExtensionManagerDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ExtensionManager * _Nonnull shared;)
+ (ExtensionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)activateWithSystemExtensionName:(NSString * _Nullable)systemExtensionName;
- (void)registerWithSystemExtensionName:(NSString * _Nonnull)systemExtensionName;
- (BOOL)isExtensionAvailableWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isExtensionAskedForUserPermissionWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)extensionFailedToInstalledWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)extensionInstallationStatusWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionManager (SWIFT_EXTENSION(AtomSDK))
@end

/// Describes additional result feedback after completion of a system extension request
typedef SWIFT_ENUM(NSInteger, ExtensionManagerResult, open) {
/// The request was successfully completed.
  ExtensionManagerResultCompleted = 0,
/// The request will be successfully completed after a reboot.
  ExtensionManagerResultWillCompleteAfterReboot = 1,
};

SWIFT_PROTOCOL("_TtP7AtomSDK24ExtensionManagerDelegate_") SWIFT_AVAILABILITY(macos,introduced=10.15)
@protocol ExtensionManagerDelegate
- (void)requestNeedsUserApprovalWithBundleId:(NSString * _Nonnull)bundleId SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)requestCompletedWithBundleId:(NSString * _Nonnull)bundleId results:(enum ExtensionManagerResult)didFinishWithResult SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)requestFailedWithBundleId:(NSString * _Nonnull)bundleId results:(NSError * _Nonnull)didFailWithError SWIFT_AVAILABILITY(macos,introduced=10.15);
@end

typedef SWIFT_ENUM(NSInteger, InternetAvailablity, closed) {
  InternetAvailablityConnected = 0,
  InternetAvailablityConnectedViaCellular = 1,
  InternetAvailablityConnectedViaCellularWithoutInternet = 2,
  InternetAvailablityConnectedViaWiFi = 3,
  InternetAvailablityConnectedViaWiFiWithoutInternet = 4,
  InternetAvailablityDetermining = 5,
  InternetAvailablityNotConnected = 6,
};

@interface NSDate (SWIFT_EXTENSION(AtomSDK))
- (NSString * _Nonnull)getDateInStringWithFormat:(NSString * _Nonnull)format SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSDictionary<KeyType, ObjectType> (SWIFT_EXTENSION(AtomSDK))
@property (nonatomic, readonly, copy) NSString * _Nullable jsonString;
@end

@class NSOperation;
SWIFT_CLASS("_TtC7AtomSDK13ParallelQueue")
@interface ParallelQueue : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithMaxOperation:(NSInteger)withMaxOperation OBJC_DESIGNATED_INITIALIZER;
- (void)cancelAllOperations;
- (void)initiazeQueue;
- (void)addWithOperation:(NSOperation * _Nonnull)operation;
- (void)addOperationWithBlock:(void (^ _Nonnull)(void))withBlock;
- (void)addOperationBulkWithBlockBulk:(void (^ _Nonnull)(void))withBlockBulk andStart:(void (^ _Nonnull)(void))andStart;
- (void)addOperationWithBlock:(void (^ _Nonnull)(void))withBlock withDependency:(BOOL)withDependency;
- (void)addOperationOnceWithBlock:(void (^ _Nonnull)(void))withBlock withIdentifier:(NSString * _Nonnull)withIdentifier;
- (NSInteger)getCurrentOperationsInProgress SWIFT_WARN_UNUSED_RESULT;
- (void)suspendQueue;
- (BOOL)isQueueSuspended SWIFT_WARN_UNUSED_RESULT;
@end

enum QueueQOS : NSInteger;
SWIFT_CLASS_NAMED("QueueManager")
@interface allMembers : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)createQueueWithName:(NSString * _Nonnull)withName withQOS:(enum QueueQOS)withQOS;
- (void)addTaskInQueue:(NSString * _Nonnull)inQueue withBlock:(SWIFT_NOESCAPE void (^ _Nonnull)(void))withBlock;
@end

typedef SWIFT_ENUM(NSInteger, QueueQOS, closed) {
  QueueQOSBackground = 0,
  QueueQOSUtility = 1,
  QueueQOSDefault = 2,
  QueueQOSUserInitiated = 3,
  QueueQOSUserInteractive = 4,
  QueueQOSUnspecified = 5,
};

@class NSStream;
/// <code>SocketManager</code> is a class designed to manage socket connections, providing methods for establishing and destroying socket sessions, sending data, and handling socket events.
/// note:
/// This class inherits from <code>NSObject</code> and conforms to <code>StreamDelegate</code> to support Objective-C interoperability.
SWIFT_CLASS("_TtC7AtomSDK13SocketManager")
@interface SocketManager : NSObject <NSStreamDelegate>
/// Handles stream events and invokes the corresponding callbacks.
/// \param aStream The stream.
///
/// \param eventCode The event code.
///
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7AtomSDK15StringUtilities")
@interface StringUtilities : NSObject
+ (NSString * _Nonnull)htmlToString:(NSString * _Nonnull)inputString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7AtomSDK12WireGuardKey")
@interface WireGuardKey : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSString * _Nonnull)getPublicKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getPrivateKey SWIFT_WARN_UNUSED_RESULT;
+ (WireGuardKey * _Nonnull)generateKeyPair SWIFT_WARN_UNUSED_RESULT;
+ (WireGuardKey * _Nonnull)getLastCreatedKey SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef ATOMSDK_SWIFT_H
#define ATOMSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AtomCore;
@import Foundation;
@import ObjectiveC;
@import SystemExtensions;
#endif

#import <AtomSDK/AtomSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AtomSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class AtomCountry;
@class AtomLocation;
@class NSString;
@interface AtomManager (SWIFT_EXTENSION(AtomSDK))
- (AtomCountry * _Nullable)findClosestCountryWithUserLocation:(AtomCountry * _Nonnull)userLocation countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (AtomLocation * _Nullable)findClosestLocationWithUserLocation:(AtomCountry * _Nonnull)userLocation countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (AtomCountry * _Nullable)findCountryWithCountry:(AtomCountry * _Nonnull)country countryList:(NSArray<AtomCountry *> * _Nonnull)countryList SWIFT_WARN_UNUSED_RESULT;
- (void)shouldAllowDialingWithIPWithDomain:(NSString * _Nonnull)domain completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

enum AtomOnDemandRuleType : NSInteger;
enum AtomOnDemandInterfaceType : NSInteger;
@class NSURL;
/// Base class for Atom On-Demand VPN rules.
/// This class provides the common properties for all types of On-Demand rules,
/// such as the rule type, interface type, SSID match, DNS match, and probe URL.
/// Use subclasses such as <code>AtomOnDemandConnectRule</code>, <code>AtomOnDemandDisconnectRule</code>,
/// <code>AtomOnDemandIgnoreRule</code>, or <code>AtomOnDemandEvaluateConnectionRule</code> for specific behaviors.
SWIFT_CLASS("_TtC7AtomSDK16AtomOnDemandRule")
@interface AtomOnDemandRule : NSObject
/// The type of the On-Demand rule.
@property (nonatomic, readonly) enum AtomOnDemandRuleType type;
/// Optional array of Wi-Fi SSIDs to match.
/// If nil, the rule applies to all SSIDs.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable SSIDMatch;
/// Optional array of DNS search domains to match.
/// If nil, the rule does not evaluate search domains.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsSearchDomains;
/// Optional array of DNS server IP addresses to match.
/// If nil, the rule does not evaluate DNS server addresses.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsServerAddresses;
/// The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any).
/// Default is <code>.any</code>.
@property (nonatomic) enum AtomOnDemandInterfaceType interfaceType;
/// Optional HTTP or HTTPS URL to probe for connectivity.
/// The VPN may start based on the result of this probe.
@property (nonatomic, copy) NSURL * _Nullable probeURL;
/// Initializes a new AtomOnDemandRule with the specified rule type.
/// \param type The type of the On-Demand rule (connect, disconnect, ignore, or evaluate connection).
///
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an On-Demand VPN rule that triggers the VPN to connect automatically.
/// Use this rule to specify when the VPN should start connecting based on network interfaces
/// and optional Wi-Fi SSIDs. This class is part of the AtomSDK On-Demand rules system.
SWIFT_CLASS("_TtC7AtomSDK23AtomOnDemandConnectRule")
@interface AtomOnDemandConnectRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandConnectRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Represents an On-Demand VPN rule that triggers the VPN to disconnect automatically.
/// Use this rule to specify when the VPN should stop or disconnect based on network interfaces
/// and optional Wi-Fi SSIDs. This class is part of the AtomSDK On-Demand rules system.
SWIFT_CLASS("_TtC7AtomSDK26AtomOnDemandDisconnectRule")
@interface AtomOnDemandDisconnectRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandDisconnectRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

@class AtomOnDemandEvaluateConnectionRuleItem;
/// Represents an On-Demand VPN rule that evaluates network connections and determines
/// whether the VPN should connect based on the defined connection rule items.
/// This rule type is part of the AtomSDK On-Demand rules system. It allows specifying multiple
/// destinations and corresponding actions to fine-tune when the VPN should start automatically.
SWIFT_CLASS("_TtC7AtomSDK34AtomOnDemandEvaluateConnectionRule")
@interface AtomOnDemandEvaluateConnectionRule : AtomOnDemandRule
/// An array of AtomOnDemandEvaluateConnectionRuleItem objects.
/// Each item is evaluated in order against network connections to determine the VPN action.
@property (nonatomic, copy) NSArray<AtomOnDemandEvaluateConnectionRuleItem *> * _Nullable connectionRules;
/// Initializes a new AtomOnDemandEvaluateConnectionRule.
/// \param connectionRules An array of AtomOnDemandEvaluateConnectionRuleItem objects defining the evaluation rules.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithConnectionRules:(NSArray<AtomOnDemandEvaluateConnectionRuleItem *> * _Nonnull)connectionRules interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Specifies the action to take when a network connection matches an Atom On-Demand Evaluate Connection rule item.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandEvaluateConnectionRuleAction, open) {
/// Start the VPN if connections to the matching hostname cannot be resolved.
  AtomOnDemandEvaluateConnectionRuleActionConnectIfNeeded = 0,
/// Do not start the VPN.
  AtomOnDemandEvaluateConnectionRuleActionNeverConnect = 1,
};

/// Represents a single connection evaluation rule item for Atom On-Demand Evaluate Connection rules.
/// Each item defines a set of destination domains and the action to take if a network connection
/// matches any of these domains. Optionally, DNS servers and a probe URL can be provided to assist
/// in evaluating connectivity.
SWIFT_CLASS("_TtC7AtomSDK38AtomOnDemandEvaluateConnectionRuleItem")
@interface AtomOnDemandEvaluateConnectionRuleItem : NSObject
/// The list of destination host domains to match against.
/// If the host name of the network connection being established matches any of these domains,
/// this rule item is considered applicable.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull matchDomains;
/// The action to take when the connection matches this rule item.
@property (nonatomic, readonly) enum AtomOnDemandEvaluateConnectionRuleAction action;
/// Optional DNS servers to use when evaluating connectivity to the destination hosts.
/// Used if <code>action</code> is <code>connectIfNeeded</code>.
@property (nonatomic, copy) NSArray<NSString *> * _Nullable dnsServers;
/// Optional HTTP or HTTPS URL to probe for connectivity.
/// If the probe request fails (e.g., returns a non-200 response) and <code>action</code> is <code>connectIfNeeded</code>,
/// the VPN is started.
@property (nonatomic, copy) NSURL * _Nullable probeURL;
/// Initializes a new AtomOnDemandEvaluateConnectionRuleItem.
/// \param matchDomains An array of host domains to match.
///
/// \param action The action to take when the network connection matches one of the domains.
///
/// \param dnsServers Optional array of DNS servers for evaluating connectivity.
///
/// \param probeURL Optional URL to probe for connectivity.
///
- (nonnull instancetype)initWithMatchDomains:(NSArray<NSString *> * _Nonnull)matchDomains action:(enum AtomOnDemandEvaluateConnectionRuleAction)action dnsServers:(NSArray<NSString *> * _Nullable)dnsServers probeURL:(NSURL * _Nullable)probeURL OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an On-Demand VPN rule that leaves the VPN connection state unchanged.
/// Use this rule to specify networks or conditions where the VPN should neither connect nor disconnect.
/// The current VPN connection state is preserved when this rule matches.
SWIFT_CLASS("_TtC7AtomSDK22AtomOnDemandIgnoreRule")
@interface AtomOnDemandIgnoreRule : AtomOnDemandRule
/// Initializes a new AtomOnDemandIgnoreRule.
/// \param SSIDMatch An optional array of Wi-Fi SSIDs to match. If nil or empty, the rule applies to all Wi-Fi networks.
///
/// \param interfaceType The network interface type to which this rule applies (Wi-Fi, Cellular, Ethernet, or Any). Default is <code>.any</code>.
///
- (nonnull instancetype)initWithSSIDMatch:(NSArray<NSString *> * _Nullable)SSIDMatch interfaceType:(enum AtomOnDemandInterfaceType)interfaceType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum AtomOnDemandRuleType)type SWIFT_UNAVAILABLE;
@end

/// Represents the network interface type to which an Atom On-Demand rule applies.
/// Use this to specify whether a rule applies to Wi-Fi, Cellular, Ethernet, or any network interface.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandInterfaceType, open) {
/// The rule applies to any network interface.
  AtomOnDemandInterfaceTypeAny = 0,
/// The rule applies to Ethernet connections (macOS and tvOS only).
  AtomOnDemandInterfaceTypeEthernet = 1,
/// The rule applies to Wi-Fi connections.
  AtomOnDemandInterfaceTypeWifi = 2,
/// The rule applies to Cellular connections (iOS only).
  AtomOnDemandInterfaceTypeCellular = 3,
};

/// Represents the type of an Atom On-Demand VPN rule.
/// Used to indicate the action that should be taken when a network connection
/// matches the conditions of the rule.
typedef SWIFT_ENUM(NSInteger, AtomOnDemandRuleType, open) {
/// Start the VPN connection when the rule matches.
  AtomOnDemandRuleTypeConnect = 0,
/// Disconnect the VPN connection when the rule matches.
  AtomOnDemandRuleTypeDisconnect = 1,
/// Leave the VPN connection state unchanged when the rule matches.
  AtomOnDemandRuleTypeIgnore = 2,
/// Evaluate the network connection against a set of connection rules
/// and determine whether the VPN should connect.
  AtomOnDemandRuleTypeEvaluateConnection = 3,
};

SWIFT_CLASS("_TtC7AtomSDK32AtomSDKDarwinNotificationManager")
@interface AtomSDKDarwinNotificationManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AtomSDKDarwinNotificationManager * _Nonnull shared;)
+ (AtomSDKDarwinNotificationManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)postNotificationWithName:(NSString * _Nonnull)name userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
- (void)startObservingWithName:(NSString * _Nonnull)name callback:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable))callback;
- (void)stopObservingWithName:(NSString * _Nonnull)name;
@end

SWIFT_CLASS("_TtC7AtomSDK13AtomSDKLogger")
@interface AtomSDKLogger : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL IS_AUTOMATION_LOGS_ENABLED;)
+ (BOOL)IS_AUTOMATION_LOGS_ENABLED SWIFT_WARN_UNUSED_RESULT;
+ (void)automationLoggerWithStr:(NSString * _Nonnull)str;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents the configuration parameters for AtomShield functionality.
SWIFT_CLASS("_TtC7AtomSDK16AtomShieldConfig")
@interface AtomShieldConfig : NSObject
/// The IP address for the AtomShield socket connection.
@property (nonatomic, copy) NSString * _Nonnull socketIP;
/// The port number for the AtomShield socket connection.
@property (nonatomic, copy) NSString * _Nonnull socketPort;
/// The features array for the AtomShield services.
@property (nonatomic, strong) NSArray * _Nonnull atomShieldFeatures;
/// The maximum number of retry attempts for establishing a Tracker Blocker socket connection.
@property (nonatomic) NSInteger retryCountForTBSocketConnection;
/// The time interval, in seconds, for updating the Tracker Blocker.
@property (nonatomic) NSInteger timeIntervalForTBUpdateInSeconds;
/// The timeout duration, in seconds, for the Tracker Blocker socket connection.
@property (nonatomic) NSInteger timeoutForTBSocketConnectionInSeconds;
/// Initializes a new instance of <code>AtomShieldConfig</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7AtomSDK14AtomShieldData")
@interface AtomShieldData : NSObject
- (NSInteger)getTotalCount SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <code>AtomShieldMPStats</code> is an Objective-C compatible class representing statistics related to telemetries.
/// note:
/// This class inherits from <code>NSObject</code> to support Objective-C interoperability.
SWIFT_CLASS("_TtC7AtomSDK17AtomShieldMPStats")
@interface AtomShieldMPStats : NSObject
/// The IP address of the socket.
@property (nonatomic, copy) NSString * _Nonnull socketIP;
/// The port of the socket.
@property (nonatomic, copy) NSString * _Nonnull socketPort;
/// The response received from the socket.
@property (nonatomic, copy) NSString * _Nonnull socketResponse;
/// The error code associated with the socket.
@property (nonatomic) NSInteger socketErrorCode;
/// The error message associated with the socket.
@property (nonatomic, copy) NSString * _Nonnull socketErrorMessage;
/// Additional inner error message associated with the socket.
@property (nonatomic, copy) NSString * _Nonnull socketErrorInnerMessage;
/// The type of feature requested by user.
@property (nonatomic, copy) NSString * _Nonnull featureType;
/// Initializes a new instance of <code>AtomShieldMPStats</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AtomShieldManagerDelegate;
@class NSError;
/// Manages the socket connection and provides methods to start, stop, and manage Atom Shield features.
SWIFT_CLASS("_TtC7AtomSDK17AtomShieldManager")
@interface AtomShieldManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onSendAtomShieldTelemetriesClosure)(NSInteger, AtomShieldMPStats * _Nullable);
@property (nonatomic, strong) id <AtomShieldManagerDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AtomShieldManager * _Nonnull shared;)
+ (AtomShieldManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isAtomShieldConnected;
/// Default init method for the class.
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Starts the connection to the AtomShieldService with the given shield configurations.
/// \param atomShieldConfig The atomShield configurations.
///
- (void)startConnectionWithAtomShieldConfig:(AtomShieldConfig * _Nonnull)atomShieldConfig isReconnecting:(BOOL)isReconnecting;
- (void)stopConnectionWithCompletionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
/// Executes an error with the given shield status.
/// \param status The AtomShield status.
///
/// \param error The AtomShield error.
///
/// \param message The AtomShield message.
///
- (void)executeErrorWithStatus:(AtomShieldStatus)status error:(NSError * _Nullable)error message:(NSString * _Nullable)message;
@end

/// Interface for receiving callbacks related to AtomShield events.
SWIFT_PROTOCOL("_TtP7AtomSDK25AtomShieldManagerDelegate_")
@protocol AtomShieldManagerDelegate
/// Invokes when the status of AtomShield changes.
/// \param status The AtomShield status.
///
/// \param error The AtomShield error.
///
/// \param message The AtomShield message.
///
- (void)onAtomShieldStatusChangeWithStatus:(AtomShieldStatus)status error:(NSError * _Nullable)error message:(NSString * _Nullable)message;
/// Invokes when data related to AtomShield, such as tracker blocker information, is received.
/// \param data The AtomShield data.
///
- (void)onAtomShieldDataReceivedWithData:(AtomShieldData * _Nullable)data;
@end

@class AccessTokenModel;
@class ApiBaseUrlModel;
@class AtomConfiguration;
SWIFT_CLASS("_TtC7AtomSDK14Authentication")
@interface Authentication : NSObject <ManagerProtocol>
@property (nonatomic, strong) AccessTokenModel * _Nullable accessToken;
@property (nonatomic, copy) NSString * _Nullable activeBaseUrl;
@property (nonatomic, strong) ApiBaseUrlModel * _Nullable apiUrl;
@property (nonatomic, strong) AtomConfiguration * _Nullable atomConfiguration;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Authentication * _Nonnull sharedManager;)
+ (Authentication * _Nonnull)sharedManager SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedManager:(Authentication * _Nonnull)value;
+ (void)setupWithAtomConfiguration:(AtomConfiguration * _Nullable)atomConfiguration baseUrlModel:(ApiBaseUrlModel * _Nonnull)baseUrlModel activeURL:(NSString * _Nullable)activeURL;
- (void)generateAccessTokenWithAuthToken:(void (^ _Nonnull)(AccessTokenModel * _Nullable, NSError * _Nullable))authToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum InternetAvailablity : NSInteger;
SWIFT_PROTOCOL("_TtP7AtomSDK20ConnectivityDelegate_")
@protocol ConnectivityDelegate
- (void)updateConnectionStatus:(enum InternetAvailablity)status;
@end

SWIFT_CLASS("_TtC7AtomSDK18ConnectivityHelper")
@interface ConnectivityHelper : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ConnectivityHelper * _Nonnull shared;)
+ (ConnectivityHelper * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hostNames;
@property (nonatomic) NSInteger hostIndex;
@property (nonatomic, strong) id <ConnectivityDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startHostAt:(NSInteger)index;
- (void)setupReachability:(NSString * _Nullable)hostName useClosures:(BOOL)useClosures;
- (void)startNotifier;
- (void)stopNotifier;
- (void)stopConnectivityChecks;
- (void)checkBrowsingWithUrl:(NSString * _Nonnull)withUrl withCompletion:(void (^ _Nonnull)(BOOL))withCompletion;
@end

SWIFT_CLASS("_TtC7AtomSDK15ExtensionHolder") SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface ExtensionHolder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class OSSystemExtensionRequest;
@class OSSystemExtensionProperties;
SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionHolder (SWIFT_EXTENSION(AtomSDK)) <OSSystemExtensionRequestDelegate>
- (void)request:(OSSystemExtensionRequest * _Nonnull)request didFinishWithResult:(OSSystemExtensionRequestResult)result;
- (OSSystemExtensionReplacementAction)request:(OSSystemExtensionRequest * _Nonnull)request actionForReplacingExtension:(OSSystemExtensionProperties * _Nonnull)existing withExtension:(OSSystemExtensionProperties * _Nonnull)ext SWIFT_WARN_UNUSED_RESULT;
- (void)requestNeedsUserApproval:(OSSystemExtensionRequest * _Nonnull)request SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)request:(OSSystemExtensionRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end

@protocol ExtensionManagerDelegate;
SWIFT_CLASS("_TtC7AtomSDK16ExtensionManager") SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionManager : NSObject
@property (nonatomic, weak) id <ExtensionManagerDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ExtensionManager * _Nonnull shared;)
+ (ExtensionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)activateWithSystemExtensionName:(NSString * _Nullable)systemExtensionName;
- (void)registerWithSystemExtensionName:(NSString * _Nonnull)systemExtensionName;
- (BOOL)isExtensionAvailableWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isExtensionAskedForUserPermissionWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)extensionFailedToInstalledWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)extensionInstallationStatusWithBundleId:(NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_AVAILABILITY(macos,introduced=10.15) SWIFT_AVAILABILITY(macos_app_extension,introduced=10.15)
@interface ExtensionManager (SWIFT_EXTENSION(AtomSDK))
@end

/// Describes additional result feedback after completion of a system extension request
typedef SWIFT_ENUM(NSInteger, ExtensionManagerResult, open) {
/// The request was successfully completed.
  ExtensionManagerResultCompleted = 0,
/// The request will be successfully completed after a reboot.
  ExtensionManagerResultWillCompleteAfterReboot = 1,
};

SWIFT_PROTOCOL("_TtP7AtomSDK24ExtensionManagerDelegate_") SWIFT_AVAILABILITY(macos,introduced=10.15)
@protocol ExtensionManagerDelegate
- (void)requestNeedsUserApprovalWithBundleId:(NSString * _Nonnull)bundleId SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)requestCompletedWithBundleId:(NSString * _Nonnull)bundleId results:(enum ExtensionManagerResult)didFinishWithResult SWIFT_AVAILABILITY(macos,introduced=10.15);
- (void)requestFailedWithBundleId:(NSString * _Nonnull)bundleId results:(NSError * _Nonnull)didFailWithError SWIFT_AVAILABILITY(macos,introduced=10.15);
@end

typedef SWIFT_ENUM(NSInteger, InternetAvailablity, closed) {
  InternetAvailablityConnected = 0,
  InternetAvailablityConnectedViaCellular = 1,
  InternetAvailablityConnectedViaCellularWithoutInternet = 2,
  InternetAvailablityConnectedViaWiFi = 3,
  InternetAvailablityConnectedViaWiFiWithoutInternet = 4,
  InternetAvailablityDetermining = 5,
  InternetAvailablityNotConnected = 6,
};

@interface NSDate (SWIFT_EXTENSION(AtomSDK))
- (NSString * _Nonnull)getDateInStringWithFormat:(NSString * _Nonnull)format SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSDictionary<KeyType, ObjectType> (SWIFT_EXTENSION(AtomSDK))
@property (nonatomic, readonly, copy) NSString * _Nullable jsonString;
@end

@class NSOperation;
SWIFT_CLASS("_TtC7AtomSDK13ParallelQueue")
@interface ParallelQueue : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithMaxOperation:(NSInteger)withMaxOperation OBJC_DESIGNATED_INITIALIZER;
- (void)cancelAllOperations;
- (void)initiazeQueue;
- (void)addWithOperation:(NSOperation * _Nonnull)operation;
- (void)addOperationWithBlock:(void (^ _Nonnull)(void))withBlock;
- (void)addOperationBulkWithBlockBulk:(void (^ _Nonnull)(void))withBlockBulk andStart:(void (^ _Nonnull)(void))andStart;
- (void)addOperationWithBlock:(void (^ _Nonnull)(void))withBlock withDependency:(BOOL)withDependency;
- (void)addOperationOnceWithBlock:(void (^ _Nonnull)(void))withBlock withIdentifier:(NSString * _Nonnull)withIdentifier;
- (NSInteger)getCurrentOperationsInProgress SWIFT_WARN_UNUSED_RESULT;
- (void)suspendQueue;
- (BOOL)isQueueSuspended SWIFT_WARN_UNUSED_RESULT;
@end

enum QueueQOS : NSInteger;
SWIFT_CLASS_NAMED("QueueManager")
@interface allMembers : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)createQueueWithName:(NSString * _Nonnull)withName withQOS:(enum QueueQOS)withQOS;
- (void)addTaskInQueue:(NSString * _Nonnull)inQueue withBlock:(SWIFT_NOESCAPE void (^ _Nonnull)(void))withBlock;
@end

typedef SWIFT_ENUM(NSInteger, QueueQOS, closed) {
  QueueQOSBackground = 0,
  QueueQOSUtility = 1,
  QueueQOSDefault = 2,
  QueueQOSUserInitiated = 3,
  QueueQOSUserInteractive = 4,
  QueueQOSUnspecified = 5,
};

@class NSStream;
/// <code>SocketManager</code> is a class designed to manage socket connections, providing methods for establishing and destroying socket sessions, sending data, and handling socket events.
/// note:
/// This class inherits from <code>NSObject</code> and conforms to <code>StreamDelegate</code> to support Objective-C interoperability.
SWIFT_CLASS("_TtC7AtomSDK13SocketManager")
@interface SocketManager : NSObject <NSStreamDelegate>
/// Handles stream events and invokes the corresponding callbacks.
/// \param aStream The stream.
///
/// \param eventCode The event code.
///
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC7AtomSDK15StringUtilities")
@interface StringUtilities : NSObject
+ (NSString * _Nonnull)htmlToString:(NSString * _Nonnull)inputString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7AtomSDK12WireGuardKey")
@interface WireGuardKey : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSString * _Nonnull)getPublicKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getPrivateKey SWIFT_WARN_UNUSED_RESULT;
+ (WireGuardKey * _Nonnull)generateKeyPair SWIFT_WARN_UNUSED_RESULT;
+ (WireGuardKey * _Nonnull)getLastCreatedKey SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
